import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import TopNav from "./_components/topnav";
import { AuthUIProvider } from "@daveyplate/better-auth-ui";
import { Providers } from "~/components/providers";
import { Toaster } from "sonner";

export const metadata: Metadata = {
    title: "PicBook",
    description: "Generated by me",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
    subsets: ["latin"],
    variable: "--font-geist-sans",
});


export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (

        <html lang="en" className={`${geist.variable}`}>
            <body className="flex flex-col gap-4">
                <Providers>
                    <TopNav />
                    {children}

                    <Toaster />
                </Providers>
            </body>
        </html>
    );
}
